### ISSUE TITLE
Switch to T-Motor or an alternative supplier instead of SunnySky

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/Sadulli#13]
We will no longer be working with SunnySky due to quality issues and the lack of adequate customer support.

**Comment by suzonch** [comment]
I'll check t motor's parameters and edit the docs

**Comment by suzonch** [comment]
How about this? This is 10mm bigger in diameter https://store.tmotor.com/goods.php?id=921
I guess we can buy 1 and test how well it fits or just calculate the values and 3d print something like that? @pavel-kirienko

**Comment by dimracer** [comment]
Let's look to MN501. It's quite expensive, but much more reliable and is lived by many customers.

**Comment by Zentrus** [comment]
Assemble Sadulli with MN501 & MN801 motors.

**Comment by Zentrus** [comment]
Successfully assembled and spun Sadulli with Scorpion MII4010 KV400.
MN501 & MN801 are too big for the enclosure - it looks ridiculous. Also, there's no way to remove the metal casing so that the thermistor can be attached to the coil.
