### ISSUE TITLE
Select proper transistors and TVS diodes

### ISSUE THREAD

**Issue by dimracer** [Zubax/Sadulli#2]
Currently TVS diodes do not save the transistors. And transistors fail after the full motor brake without battery. Selection technique is presented [here](https://forum.zubax.com/t/how-to-select-the-tvs-diode-protection/1544).

**Comment by j3qq4hch** [comment]
Найти более подходящий TVS  диод не представляется возможным. 
На самом деле никакой подобного рода ESC не предназначен для того режима работы, в котором один садулли вышел из строя. Более того, точные причины его выхода из строя едва ли ясны, ведь это единичное событие, об обстоятельствах которого нам известно из третьих рук.

Нет никаких причин для внесения каких-либо изменений в садулли, и самое правильное - ничего не делать. Однако, если нас обуревает жажда деятельности, мы можем немного починить и то, что не сломалось. 

Максимальное напряжение работы садулли определяется силовой платой. На ней это напряжение зависит от:

1) Транзисторов
2) Керамических конденсаторов
3) Электролитических конденсаторов
4) TVS диодов

Текущее положение дел:
1) Транзисторы BUK7K13-60EX с Vds_max транзисторов - 40 В
2) Vmax  керамических конденсаторов - 50 В
3) Vmax электролитических конденсаторов 50 В
4) Voltage - Reverse Standoff 33 В, Voltage - Clamping_max - 53.3 В

Из всех этих компонентов наиболее уязвимыми выглядят транзисторы. Их и можно было бы заменить на совместимые по футпринту транзисторы с  Vds_max = 60 В (BUK7K13-60EX). Однако, у таких транзисторов несколько выше сопротивление открытого канала (примерно в полтора раза).  Садулли - очень компактное устройство, и радиатор на нем не может рассеять слишком много тепла. С некоторыми оговорками мы можем рассчитывать, что он справится с 20 ваттами потерь.  Ниже представлены графики зависимости потерь в садулли от потребляемой от источника питания мощности  при напряжении 26.4 вольта (это напряжение разряженной 8S батареи). 

Садулли в текущем виде
![current](https://user-images.githubusercontent.com/9300016/79463750-eac01180-8001-11ea-937b-72c30ebdc040.png)
Садулли после гипотетической замены транзисторов
![new](https://user-images.githubusercontent.com/9300016/79463806-f90e2d80-8001-11ea-8003-ff0ff5bf26f4.png)

Конечно, это несколько идеализированная ситуация, в  действительности все может быть несколько хуже. Однако, уже из этих картинок видно, что  замена транзисторов заметно ухудшит эффективность садулли.

**Comment by dimracer** [comment]
Транзисторы менять не нужно. Вполне достаточно заменить TVS диоды. Впрочем, как я вижу, вы уже заменили их на PTVS33VP1UTP. Они для защиты от кратковременных выбросов напряжения при резком торможении вполне сгодятся. 
Хорошо бы заменить TVS диоды на уже собранных Sadulli. Там сейчас стоят PTVS36VP1UP,115.

**Comment by pavel-kirienko** [comment]
@dimracer what's the status here?

**Comment by dimracer** [comment]
Нужно заменить диоды на уже собранных платах. В документации вопрос решен.

**Comment by pavel-kirienko** [comment]
Okay, so this issue is not related to engineering or product development, I suggest closing it. Please task Farzan on Trello to resolder the TVS diodes.
