### ISSUE TITLE
Замена моторов

### ISSUE THREAD

**Issue by j3qq4hch** [Zubax/Sadulli#5]
В текущей версии садулли используются следующие моторы:
* [V4006 KV320](http://en.rcsunnysky.com/v-multi-rotorefficiencytype/1081.html) с пропеллером 15 дюймов
* [V4014 KV330](http://en.rcsunnysky.com/v-multi-rotorefficiencytype/1083.html) с пропеллером 17 дюймов

Предполагается, что садулли может питаться от 4-8S аккамуляторов. Учитывая неполную утилизацию напряжения, при разряженной 8S батарее это дает

* RPMmax = 4438 - для маленького садулли
* RPMmax = 4577 - для большого садулли

Ниже представлены графики зависимости тяги используемых пропеллеров от оборотов в минуту

Пропеллер 15 дюймов
![image](https://user-images.githubusercontent.com/9300016/79466082-c44fa580-8004-11ea-89f4-d9d1d7045253.png)

Пропеллер 17 дюймов
![image](https://user-images.githubusercontent.com/9300016/79466010-b13cd580-8004-11ea-9c4d-c095334b22a1.png)

Видно, что при питании от 8S аккумулятора (а это максимально допустимый для садулли), можно БЕЗОПАСНО рассчитывать на тягу:

* 1200 грамм для маленького садулли
* 2000 грамм для большого садулли

Это фактически ограничивает рабочий диапазон напряжения садулли диапазоном напряжения 8S батареи, т.к. со всеми другими батареями крайне малая максимальная тяга садулли лишает использование садулли всякого смысла. 

Мне нравятся моторы sunnysky, можно было бы перейти на те же модели, но с несколько бОльшим KV:
* KV380 для маленького садулли
* KV400 для большого садулли

Однако, я не уверен, что этого достаточно

**Comment by pavel-kirienko** [comment]
Closing as low priority; will discuss internally as necessary
