### ISSUE TITLE
Manufacturing instructions: require a particular motor phase ordering

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/Sadulli#6]
The manufacturing instructions shall define a specific phase ordering to ensure that the direction of rotation is consistent.

**Comment by j3qq4hch** [comment]
Не думаю, что это возможно

**Comment by pavel-kirienko** [comment]
Please explain why. cc @dimracer

**Comment by j3qq4hch** [comment]
Потому что производитель моторов не гарантирует какого-то определенного расположения проводов. Я не знаю как это сделать механически. Выбор направления должен быть реализован как-то при настройке и тестировании

**Comment by pavel-kirienko** [comment]
As discussed at the call, this is solvable by attaching the motor phases to a sinewave voltage source (e.g., another myxa running continuously in the scalar control mode) just before soldering the phases. @j3qq4hch please introduce this step with a detailed description of the process into the assembly manual.

**Comment by j3qq4hch** [comment]
You should stop ignoring the contents of our calls (although due to the calls' length it may be not that easy). The rotation direction has nothing to do with mechanical assembly of the device. It is already very inconvenient process, there is no need to make it even worse. 
Of course, you may have some doubts in this claim, as it looks pretty straight-froward in the video. In this case, I suggest you try to assemble one device personally. And also try the method you propose. I am sure, after that, we will surely reach solidarity in this question.

**Comment by pavel-kirienko** [comment]
Are you sure you understand the objective here? You can't just say that there is no need to do something when the need is very clearly stated in the first post. I have proposed a solution that seems sensible and I would gladly run a practical demo myself to showcase it. In the future, please desist from rejecting proposals unless you understand the objective and have viable counter-arguments. Your lack of desire to do something does not count as one.

**Comment by j3qq4hch** [comment]
You definetly misunderstand the point. It is not my lack of desire to do something, it is about impracticality of the idea, while there exists a more sensible solution. Also, in the future, please desist from pointing anyone what he or she should do in the future.

**Comment by pavel-kirienko** [comment]
Alex, this is not how constructive discourse works. There is a business requirement and your job is either to identify how it can be implemented, to suggest how it can be achieved using alternative means, or to question its validity. A flat proposal to forget about the requirement or an unsupported claim of its non-viability is not helping anybody. You can't work with us unless you follow the basic principles of constructive discussion. Please adjust your future behavior accordingly.

**Comment by dimracer** [comment]
Аргумент Павла по поводу возможного сбоя направления после сброса настроек звучит убедительно до тех пор, пока не будет закрыт [этот тикет](https://github.com/Zubax/telega/issues/320). Решение задачи сохранения настроек позволит предотвратить сброс всех настроек при смене прошивки. Сам по себе же сброс настроек пользователем подразумевает проверку и донастройку привода перед запуском, в том числе и настройку направления вращения. 
В конечном варианте конечно же выбор направления вращения должен быть реализован программно. И этот пункт следует включить в процесс тестирования Sadulli в Dr_Watson. 

Я не уверен, что включать муху - это простое решение. Хотя вообще сложно говорить о простом решении для какого-нибудь рабочего на сборочной линии, когда перед ним возникает задача что-либо перетыкать туда-сюда, да еще и на включенном устройстве. Тем не менее, на мой взгляд, можно незначительно упростить эту операцию если использовать обычный dc источник напряжения (достаточно 1 V, 0.5 А). 
Последовательность операций будет выглядеть примерно так:
1. Подключить один из проводов мотора к минусу источника. Обозначить этот провод как "А".
2. Принять за заданное направление вращения мотора, например, CW. Подключить любой из оставшихся проводов (назовем его провод 2) к плюсу источника. Заметить в каком направлении сдвинулся ротор. Отсоединить провод от источника.
3. Подключить третий провод к плюсу источника и заметить направление, в которое сдвинулся ротор. 
4. Если в п 2 и 3 оба раза направление было CW, то обозначить провод 2 как "B", провод 3 как "C". Если же направления были разные - то обозначить наоборот "С" и "B".

**Comment by pavel-kirienko** [comment]
It's far more complex than what I proposed. The method that I described amounts to the following steps:

1. Connect the motor phase wires to the Myxa and notice the direction of rotation. Disconnect the phase wires.
2. If the rotor spins clockwise, solder the wires as-is. Otherwise, swap any two phases.

That's it. The assembly worker doesn't get involved with Myxa because it keeps running in the scalar control mode continuously.

**Comment by dimracer** [comment]
Этот метод предполагает, что скалярный режим преднастроен под данный конкретный мотор. Если взять другой мотор, то та же муха может не закрутить его. 
Мне оба метода не нравятся. Оба метода - "костыли". Предложенный мной метод разве что более универсальный и не требует никакой преднастройки. Поэтому, чтобы не разводить здесь длинную дискусиию, предлагаю оставить конкретный метод на выбор исполнителя, в данном случае Фарзана. Не стоит больше тратить на это время. Александр, опишите, пожалуйста оба метода в инструкции.

**Comment by j3qq4hch** [comment]
После сборки устройства его все равно нужно подключить к UAVCAN GUI TOOL чтобы убедиться, что в процессе сборки ничего не закоротило и все работает. На этом шаге и нужно определить направление вращения. Это не привносит никакого дополнительного неудобства и потенциальной возможности что-нибудь повредить, а также практически не увеличивает время сборки.

**Comment by pavel-kirienko** [comment]
> Этот метод предполагает, что скалярный режим преднастроен под данный конкретный мотор. Если взять другой мотор, то та же муха может не закрутить его.

This is not true. You can see that yourself by running a trivial test. Set the V/Hz at a sufficiently high value and you will get any motor to spin. Are there any other arguments?

**Comment by j3qq4hch** [comment]
Я все еще не думаю, что переподключение фаз к садулли в процессе сборки возможно. Однако, если нам так уж нужно определять направление вращения мотора на этапе производства мы могли бы создать для этого несложную машину. Вот как это выглядит у меня в голове. 
1) Перед началом сборки устройства на мотор наносится МЕТКА (Стикер с 3 белыми полосками на разном расстоянии друг от друга). 
2) После сборки садулли помещается в МАШИНУ и подключается по UAVCAN к dr watson. Машина также должна быть подключена к dr watson каким-нибудь способом (вероятно, по UAVCAN). dr watson начинает вращать мотор. МАШИНА  состоит из, например, бабеля, к которому подключен светодиод и фотодиод. МАШИНА светит на мотор, определяет направление его вращения по интервалам между срабатываниями фотодиода и сообщает об этом  dr watson, который затем может его инвертировать, если это необходимо. 
Такой способ позволит не усложнять сборку и, т.к. все равно необходимо добавление стикера на мотор, даст возможность дополнительного брендирования мотора. А также из процесса полностью исключается человеческий фактор. 

Однако, это потребует некоторых усилий для создания МАШИНЫ, которые, вероятно, могут быть оправданы только в случае производства ЗНАЧИТЕЛЬНОЙ ПАРТИИ садулли, чего пока не предвидится, если я не ошибаюсь.

**Comment by j3qq4hch** [comment]
Can we close this issue?

**Comment by pavel-kirienko** [comment]
No. This will be implemented as I described when we get back to Sadulli. The discussed alternatives are unacceptable.

**Comment by pavel-kirienko** [comment]
Fixed in #8
