### ISSUE TITLE
Move the manufacturing instructions into this repo

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/Sadulli#7]
In the markdown format with images.

The images posted at https://kb.zubax.com/display/PRIVATE/Sadulli+manufacturing+instructions require compression. The entire text has to be rewritten to be readable.

**Comment by j3qq4hch** [comment]
There is a PR about this issue. Can it be closed?

**Comment by pavel-kirienko** [comment]
An issue cannot be closed until it is resolved, so no.

**Comment by pavel-kirienko** [comment]
Fixed in #8
